version: 2

sources:
  - name: source  
    tables:
      - name: DISCOUNT_KUPON
      - name: customers     
      - name: marketing_spend   
      - name: online_sales 

models:
  - name: stg_disc_kupon
    description: "A starter dbt model"
    columns:
      - name: COUPON_CODE
        description: "The primary key for this table"
        data_tests:
          - not_null
    
  - name: stg_customers
    description: "A customers staging model"
    columns:
      - name: CustomerID
        description: "The primary key for this table"
        data_tests:
          - not_null 
          - unique 
  
  - name: stg_marketing_spend
    description: "A marketing_spend staging model"
    columns:
      - name: Date
        description: "The primary key for this table"
        data_tests:
          - not_null

  - name: stg_online_sales
    description: "A online sales staging model"
    columns:
      - name: Transaction_ID
        description: "The primary key for this table"
        data_tests:
          - not_null 

