
version: 2

sources:
  - name: source  
    tables:
      - name: DISCOUNT_KUPON
      - name: customers     
      - name: marketing_spend   
      - name: online_sales 

models:
  - name: stg_disc_kupon
    description: "A starter dbt model"
    columns:
      - name: COUPON_CODE
        description: "The primary key for this table"
        data_tests:
          - not_null

